apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cr-network-worker
  labels:
    app: cr-network-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cr-network-worker
  template:
    metadata:
      labels:
        pod: cr-network-worker
    spec:
      containers:
        - name: cr-network-worker
          image: thomasstruble/askcos_public
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 2 -Q cr_network_worker -n cr_network_worker@%h"]
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: RABBIT_HOST
              value: rabbit-service
            - name: KERAS_BACKEND
              value: theano

