apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tb-coordinator-mcts
  labels:
    app: tb-coordinator-mcts
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: tb-coordinator-mcts
  template:
    metadata:
      labels:
        pod: tb-coordinator-mcts
    spec:
      containers:
        - name: tb-coordinator-mcts
          image: thomasstruble/askcos_public
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 2 -Q tb_coordinator_mcts -n tb_coordinator_mcts@%h"]
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: RABBIT_HOST
              value: rabbit-service
            - name: KERAS_BACKEND
              value: theano

