apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: te-coordinator
  labels:
    app: te-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: te-coordinator
  template:
    metadata:
      labels:
        pod: te-coordinator
    spec:
      containers:
        - name: te-coordinator
          image: thomasstruble/askcos_public
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 2 -Q te_coordinator -n te_coordinator@%h"]
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: RABBIT_HOST
              value: rabbit-service
            - name: KERAS_BACKEND
              value: theano

